stage_name      = "develop"
prefix_role     = "lambda-role-dev"
db_name         = "pocdev"
db_user         = "userdev"
prefix_parent   = "lambda-parent-dev"
prefix_child_01 = "lambda-child-01-dev"
prefix_child_02 = "lambda-child-02-dev"
