stage_name                    = "develop"
prefix_role                   = "lambda-role-dev"
db_name                       = "pocdev"
db_user                       = "userdev"
prefix_parent                 = "lambda-parent-dev"
prefix_child_01               = "lambda-child-01-dev"
prefix_child_02               = "lambda-child-02-dev"
environment_variables_parent  = { "LAMBDA_POSTS" : "lambda-child-01-dev-poc-function", "LAMBDA_USERS" : "lambda-child-02-dev-poc-function", "REGION" : "us-east-2", "GIN_MODE" : "release" }
environment_variables_child01 = { "API_SECRET" : "1234", "API_URL" : "https://jsonplaceholder.typicode.com", "GIN_MODE" : "release" }
environment_variables_child02 = { "API_SECRET" : "1234", "API_URL" : "https://jsonplaceholder.typicode.com", "GIN_MODE" : "release" }
api_gateway_name              = "poc-api-gw"
lambda_role_name              = "poc-role"
lambda_policy_name            = "poc-policy"
lambda_function_name          = "poc-function"
